---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - oauth-cluster.yaml
  - group-admin-ldap.yaml
  - group-read-ldap.yaml
  - rbac-clusteradmin.yaml
  - rbac-cluster-read.yaml