apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nncp-bpr1pwr05-bond1-vlan-251-252.yaml  
  - nncp-bpr1pwr06-bond1-vlan-251-252.yaml
  - nncp-bpr1pwr07-bond1-vlan-251-252.yaml
  - nncp-bpr1pwr08-bond1-vlan-251-252.yaml
  - ovs-br-vmdata.yaml